# Mengizinkan Gradle menggunakan RAM maksimal 2GB dan membuka paksa gerbang modul compiler Java 21
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 --add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED --add-opens=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED --add-opens=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED --add-opens=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED --add-opens=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED

# Mengaktifkan dukungan pustaka AndroidX (Wajib untuk Jetpack Compose)
android.useAndroidX=true

# Mengatur agar gaya penulisan kode Kotlin mengikuti standar resmi JetBrains
kotlin.code.style=official
# MATIKAN FITUR JLINK UNTUK MEMECAHKAN BUG AGP 8.2.0 DENGAN JAVA 21
android.experimental.useJdkImageTransform=false
# Memaksa Gradle untuk menggunakan Java 17 lokal di folder home Anda secara permanen
org.gradle.java.home=/home/nihongo/jdk-17.0.20+8


# 🔥 OPTIMASI GRADLE
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true

# 🔥 ANDROID OPTIMASI
android.enableJetifier=true
android.useAndroidX=true
android.enableR8.fullMode=true

# 🔥 KOTLIN COMPILER CACHE
kotlin.incremental=true
kotlin.caching.enabled=true

# 🔥 MEMORY
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m